const { test, expect } = require('@playwright/test');

test('v3.3 C Class preserves rank ecology, Makashi, and command continuity metadata',async({page})=>{
  const response=await page.goto('/',{waitUntil:'domcontentloaded',timeout:30000});
  expect(response).not.toBeNull();expect(response.status()).toBeLessThan(400);
  await page.waitForFunction(()=>Boolean(window.GameTest&&window.__battleSim),null,{timeout:15000});
  const pause=page.locator('#pauseBtn');if((await pause.textContent())?.trim()==='Pause')await pause.click();
  const r=await page.evaluate(()=>{GameTest.setSeed(35000);return GameTest.state()});
  expect(r.version).toBe('3.3');
  expect(r.phase).toBe(4);
  expect(r.patchVersion).toBe('3.3.0');
  expect(r.rework).toBe('c-class-volley-drill');
  expect(r.classProgression.ePromotionXP).toBe(4);
  expect(r.classProgression.dPromotionXP).toBe(10);
  expect(r.classProgression.cPromotionXP).toBe(18);
  expect(r.classProgression.unlocked).toEqual(['F','E','D','C']);
  expect(r.classProgression.rankEcology.model).toContain('C scarce-recurring');
  expect(r.classProgression.rankEcology.eTargets.CONTEST).toBeCloseTo(.20,8);
  expect(r.classProgression.rankEcology.dTargets.CONTEST).toBeCloseTo(.04,8);
  expect(r.classProgression.rankEcology.cTargets.CONTEST).toBeCloseTo(.02,8);
  expect(r.classProgression.cClass.price).toBe(150);
  expect(r.classProgression.cClass.volleyDrill.order).toBe('VOLLEY');
  expect(r.command.commandAuthority.deathDisrupts).toBe(true);
  expect(r.command.commandAuthority.livingRetreatDisrupts).toBe(false);
  expect(r.command.commandAuthority.replacementRequiresPhysicalJoin).toBe(true);
  expect(r.command.combatContinuity.crossLaneAwareness.requiresLocalCommand).toBe(true);
  expect(r.command.lightsaberForm.unlocked).toEqual(['I Shii-Cho','II Makashi']);
  expect(r.command.lightsaberForm.formII.projectileDeflection).toBe(false);
  expect(await page.title()).toContain('Phase 4 v3.3');
  expect(await page.locator('.version').textContent()).toContain('v3.3');
});
