const { test, expect } = require('@playwright/test');
const CANONICAL_FORMS=['I Shii-Cho','II Makashi','III Soresu','IV Ataru','V Shien/Djem So','VI Niman','VII Juyo/Vaapad'];
async function openGame(page){const pageErrors=[],consoleErrors=[];page.on('pageerror',e=>pageErrors.push(e.message));page.on('console',m=>{if(m.type()==='error'&&!m.text().toLowerCase().includes('favicon'))consoleErrors.push(m.text())});const response=await page.goto('/',{waitUntil:'domcontentloaded',timeout:30000});expect(response).not.toBeNull();expect(response.status()).toBeLessThan(400);await page.waitForFunction(()=>Boolean(window.GameTest&&window.__battleSim),null,{timeout:15000});const pause=page.locator('#pauseBtn');if((await pause.textContent())?.trim()==='Pause')await pause.click();return{pageErrors,consoleErrors}}

test('deployed preview boots with Phase 3 D-Class invariants',async({page},testInfo)=>{const diagnostics=await openGame(page);const r=await page.evaluate(()=>({state:GameTest.state(),validation:GameTest.validate()}));expect(r.validation.ok).toBe(true);expect(r.validation.roadmapCount).toBe(15);expect(r.state.version).toBe('3.0');expect(r.state.phase).toBe(3);expect(r.state.economy.patch).toBe(15);expect(r.state.economy.calibrationSeriesComplete).toBe(true);expect(r.state.economy.rankPrices).toEqual({F:10,E:32,D:80});expect(r.state.economy.purchasableRanks).toEqual(['F','E','D']);expect(r.state.classProgression.ePromotionXP).toBe(4);expect(r.state.classProgression.dPromotionXP).toBe(10);expect(r.state.classProgression.dClass.reloadBonus).toBe(2);expect(r.state.classProgression.dClass.reloadMinimum).toBe(25);expect(r.state.classProgression.dClass.aimBonus).toBeCloseTo(.035,8);expect(r.state.command.maxMusketeers).toBe(14);expect(r.state.command.musket.baseReload).toBe(30);expect(r.state.command.lightsaberForm.current).toBe('I');expect(r.state.command.lightsaberForm.next).toBe('II Makashi');expect(r.state.command.lightsaberForm.forms).toEqual(CANONICAL_FORMS);expect(await page.title()).toContain('Phase 3 v3.0');expect(diagnostics.pageErrors).toEqual([]);await testInfo.attach('console-errors.json',{body:Buffer.from(JSON.stringify(diagnostics.consoleErrors,null,2)),contentType:'application/json'})});

test('D Class is both directly buyable and earnable from E at 10 XP',async({page})=>{await openGame(page);const r=await page.evaluate(()=>{GameTest.setSeed(30001);const api=__battleSim.test,g=api.generals()[0];g.money=1000;const beforeMoney=g.money,direct=api.buyMusketeer(0,'D'),afterDirectMoney=g.money,directCost=beforeMoney-afterDirectMoney;const killer=api.actors().find(a=>a.alive&&a.team===0&&!a.isCommander&&a!==direct),victim=api.actors().find(a=>a.alive&&a.team===1&&!a.isCommander);killer.rank='E';killer.xp=9;killer.earnedXP=5;const beforePromotions=GameTest.state().dPromotions[0];api.killActor(victim,killer,'test');return{directRank:direct&&direct.rank,directXP:direct&&direct.xp,directCost,killerRank:killer.rank,killerXP:killer.xp,dPromotions:GameTest.state().dPromotions[0]-beforePromotions,validation:GameTest.validate()}});expect(r.validation.ok).toBe(true);expect(r.directRank).toBe('D');expect(r.directXP).toBe(10);expect(r.directCost).toBeCloseTo(80,6);expect(r.killerRank).toBe('D');expect(r.killerXP).toBe(10);expect(r.dPromotions).toBe(1)});

test('F/E-only economy quality remains Phase-2 compatible after D unlock',async({page})=>{await openGame(page);const r=await page.evaluate(()=>{GameTest.setSeed(30003);const api=__battleSim.test,g=api.generals()[0];g.money=1000;const before=api.armyEconomyMetrics(0);api.buyMusketeer(0,'E');const after=api.armyEconomyMetrics(0);return{before,after,validation:GameTest.validate()}});expect(r.validation.ok).toBe(true);expect(r.before.rankBonus).toBe(0);expect(r.before.priceBonus).toBe(0);expect(r.after.count).toBe(15);expect(r.after.rankBonus).toBeCloseTo(1/15,8);expect(r.after.priceBonus).toBeCloseTo(1/15,8);expect(r.after.qualityBonus).toBeCloseTo(2/15,8)});

test('D assault drill is E-equivalent before siege and activates under SIEGE',async({page})=>{await openGame(page);const r=await page.evaluate(()=>{GameTest.setSeed(30002);const api=__battleSim.test,g=api.generals()[0];g.money=1000;const e=api.buyMusketeer(0,'E'),d=api.buyMusketeer(0,'D'),target=api.actors().find(a=>a.alive&&a.team===1&&!a.isCommander);const baseline={eAcc:api.shotAccuracy(e,target,120),dAcc:api.shotAccuracy(d,target,120),eReload:api.musketReloadTime(e),dReload:api.musketReloadTime(d)};GameTest.forceStance(0,'SIEGE');const assault={eAcc:api.shotAccuracy(e,target,120),dAcc:api.shotAccuracy(d,target,120),eReload:api.musketReloadTime(e),dReload:api.musketReloadTime(d)};d.xp=100;const dFloor=api.musketReloadTime(d);return{baseline,assault,dFloor,state:GameTest.state(),validation:GameTest.validate()}});expect(r.validation.ok).toBe(true);expect(r.state.command.musket.baseReload).toBe(30);expect(r.baseline.dAcc).toBeCloseTo(r.baseline.eAcc,8);expect(r.baseline.dReload).toBeCloseTo(r.baseline.eReload,8);expect(r.assault.dAcc).toBeGreaterThan(r.assault.eAcc);expect(r.assault.dReload).toBeLessThan(r.assault.eReload);expect(r.dFloor).toBe(25)});

test('General reserves D procurement for a funded siege top-off',async({page})=>{await openGame(page);const r=await page.evaluate(()=>{GameTest.setSeed(30004);const api=__battleSim.test,g=api.generals()[0],desired=14;g.money=1000;const contest=api.procurementRank(0,'CONTEST',80,desired);GameTest.forceStance(0,'SIEGE');const siege=api.procurementRank(0,'SIEGE',80,desired);return{contest,siege,validation:GameTest.validate()}});expect(r.validation.ok).toBe(true);expect(r.contest).not.toBe('D');expect(r.siege).toBe('D')});

test('300-second Phase 3 self-play remains finite and bounded',async({page},testInfo)=>{await openGame(page);const r=await page.evaluate(()=>{GameTest.setSeed(30118);const state=GameTest.advance(300);return{state,validation:GameTest.validate()}});expect(r.validation.ok).toBe(true);expect(r.state.money.every(v=>Number.isFinite(v)&&v>=-.001)).toBe(true);expect(r.state.fortresses.every(f=>Number.isFinite(f.hp)&&f.hp>=0&&f.hp<=f.maxHp)).toBe(true);const p=testInfo.outputPath('phase3-300s.png');await page.screenshot({path:p,fullPage:true});await testInfo.attach('phase3-300s.png',{path:p,contentType:'image/png'})});

test('D remains an elite minority and the economy stays bounded in 4 x 600-second samples',async({page},testInfo)=>{test.setTimeout(120000);await openGame(page);const result=await page.evaluate(()=>{const out=[];for(const seed of[30101,30102,30103,30104]){GameTest.setSeed(seed);const maxTreasury=[0,0],maxDShare=[0,0];for(let i=0;i<20;i++){GameTest.advance(30);const s=GameTest.state();for(let t=0;t<2;t++){maxTreasury[t]=Math.max(maxTreasury[t],s.money[t]);maxDShare[t]=Math.max(maxDShare[t],s.musketeers[t]?s.dclass[t]/s.musketeers[t]:0)}}const s=GameTest.snapshot();out.push({seed,validation:GameTest.validate(),maxTreasury,maxDShare,money:s.money,army:s.musketeers,eclass:s.eclass,dclass:s.dclass,rankPurchases:s.rankPurchases,ePromotions:s.ePromotions,dPromotions:s.dPromotions,netIncome:s.economy.netIncomeRates,fortresses:s.fortresses})}return out});console.log(`D_CLASS_CALIBRATION ${JSON.stringify(result)}`);await testInfo.attach('d-class-calibration.json',{body:Buffer.from(JSON.stringify(result,null,2)),contentType:'application/json'});expect(result.every(x=>x.validation.ok)).toBe(true);const maxTreasury=Math.max(...result.flatMap(x=>x.maxTreasury)),maxShare=Math.max(...result.flatMap(x=>x.maxDShare));expect(maxTreasury).toBeLessThan(3000);expect(maxShare).toBeLessThan(.30)});

test('Phase 3 natural siege remains possible across a broader nine-seed acceptance sample',async({page},testInfo)=>{test.setTimeout(180000);await openGame(page);const result=await page.evaluate(()=>{function sample(seeds){const out=[];for(const seed of seeds){GameTest.setSeed(seed);const minDistance=[Infinity,Infinity],peakUncommanded=[0,0];for(let i=0;i<120;i++){GameTest.advance(5);const s=GameTest.state();for(let t=0;t<2;t++){if(s.breachFortDistance[t]!==null)minDistance[t]=Math.min(minDistance[t],s.breachFortDistance[t]);peakUncommanded[t]=Math.max(peakUncommanded[t],s.uncommanded[t])}}const s=GameTest.snapshot();out.push({seed,validation:GameTest.validate(),fortressHits:s.fortressHits,minBreachFortDistance:minDistance.map(v=>Number.isFinite(v)?v:null),peakUncommanded,dclass:s.dclass,rankPurchases:s.rankPurchases,fortresses:s.fortresses})}return out}return{phase2Comparison:sample([21901,21902,21903]),phase3Acceptance:sample([30201,30202,30203,30204,30205,30206,30207,30208,30209])}});console.log(`NATURAL_SIEGE_COMPARISON ${JSON.stringify(result.phase2Comparison)}`);console.log(`NATURAL_SIEGE_PHASE3 ${JSON.stringify(result.phase3Acceptance)}`);await testInfo.attach('natural-siege-phase2-comparison.json',{body:Buffer.from(JSON.stringify(result.phase2Comparison,null,2)),contentType:'application/json'});await testInfo.attach('natural-siege-phase3-acceptance.json',{body:Buffer.from(JSON.stringify(result.phase3Acceptance,null,2)),contentType:'application/json'});expect(result.phase2Comparison.every(x=>x.validation.ok)).toBe(true);expect(result.phase3Acceptance.every(x=>x.validation.ok)).toBe(true);const totalHits=result.phase3Acceptance.reduce((n,x)=>n+x.fortressHits[0]+x.fortressHits[1],0);expect(totalHits).toBeGreaterThan(0)});

test('separated living commander still physically returns without early command restoration',async({page})=>{await openGame(page);const r=await page.evaluate(()=>{GameTest.setSeed(30121);const api=__battleSim.test,c=api.companies()[0][0],cmd=api.actors().find(a=>a.alive&&a.team===0&&a.isCommander&&a.company===c.id),center=api.companyCenter(0,c.id);cmd.x=center.x+400;cmd.y=center.y;const before=Math.hypot(cmd.x-center.x,cmd.y-center.y);api.updateCommander(cmd,1);const afterCenter=api.companyCenter(0,c.id),after=Math.hypot(cmd.x-afterCenter.x,cmd.y-afterCenter.y);return{before,after,separated:api.commanderInCommand(c)===null,validation:GameTest.validate()}});expect(r.validation.ok).toBe(true);expect(r.before-r.after).toBeCloseTo(28,5);expect(r.separated).toBe(true)});

test('fieldwork siege control still blocks and reopens paid D-era recruitment',async({page})=>{await openGame(page);const r=await page.evaluate(()=>{GameTest.setSeed(30122);GameTest.forceBreach(0,0,true);const api=__battleSim.test,g=api.generals()[1],blocked=api.buyMusketeer(1,'D');GameTest.forceStance(0,'CONTEST');g.money=1000;const reopened=api.buyMusketeer(1,'D');return{blocked:blocked===null,reopened:!!reopened,reopenedX:reopened&&reopened.x,reopenedRank:reopened&&reopened.rank,validation:GameTest.validate()}});expect(r.validation.ok).toBe(true);expect(r.blocked).toBe(true);expect(r.reopened).toBe(true);expect(r.reopenedRank).toBe('D');expect(r.reopenedX).toBe(2670)});

test('controlled BREACH still converts into fortress damage',async({page})=>{await openGame(page);const r=await page.evaluate(()=>{GameTest.setSeed(30119);GameTest.forceBreach(0,0,true);const before=GameTest.snapshot(),after=GameTest.advance(1);return{before,after,validation:GameTest.validate()}});expect(r.validation.ok).toBe(true);expect(r.after.fortressHits[0]).toBeGreaterThan(r.before.fortressHits[0]);expect(r.after.fortresses[1].hp).toBeLessThan(r.before.fortresses[1].hp)});

test('player-facing Pause, Speed, and Front controls work',async({page})=>{await openGame(page);const pause=page.locator('#pauseBtn'),speed=page.locator('#speedBtn'),front=page.locator('#frontBtn');await expect(pause).toHaveText('Resume');await pause.click();await expect(pause).toHaveText('Pause');await pause.click();await expect(pause).toHaveText('Resume');await speed.click();await expect(speed).toHaveText('Speed 2×');await speed.click();await expect(speed).toHaveText('Speed 4×');await speed.click();await expect(speed).toHaveText('Speed 1×');await page.evaluate(()=>{GameTest.setSeed(30120);GameTest.advance(20);document.getElementById('fieldWrap').scrollLeft=0});await front.click();await page.waitForTimeout(500);expect(await page.locator('#fieldWrap').evaluate(el=>el.scrollLeft)).toBeGreaterThan(0)});
